### ISSUE TITLE
Discussion: lazy loading MAGICCInput

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#120]
@lewisjared I find the lazy loading of MAGICCInput really confusing. I'm sure there is a super useful reason for it but I can't see it, can you just run me again through why it's helpful?

**Comment by lewisjared** [comment]
What about it is confusing? Is it the extra function call before they can be used? 

Lazy loading allows objects to refer to a specific filename without having a concrete magicc instance defined. `MAGICCData('RCP26.SCEN7')` refers to the configuration file which contains emissions for RCP2.6 independent of the MAGICC distribution being used. This object can be created in a module before a specific MAGICC instance exists. If the files were read at the time of the initialisation of the object, you could not do this because you don't have an absolute path to the file. Also what if the file doesn't exist and you actually want to create it?

The logic for reading a file is encapsulated in the `read` routine so if we want to synchronously read the files when the object is constructed, the call just has to be added to the `__init__` routine. It is also easy enough to call the read method automatically when accessing the data if it has not been explicitly called.

**Comment by znicholls** [comment]
> What about it is confusing? Is it the extra function call before they can be used?

No not quite. My thought was that `read` and `write` should have the same function signature i.e. `read(path, filename)` or `read(filename, path)`. I just couldn't quite work out how to make that logic fit with the lazy loading logic.

Do these signatures make sense to you?

```python
def read(self, filepath=None, filename=None):
    """
    Read an input file from disk

    # Parameters
    filepath (str): The directory to read the file from. This is often the
        run directory for a magicc instance. If None is passed,
        the run directory for the version of MAGICC6 included in pymagicc
        is used.
    filename (str): The filename to read. Overrides any existing values.
        If None is passed, the filename used to initialise the MAGICCData
        instance is used.
    """
```

```python
def write(self, filepath=None, filename=None):
    """
    Write an input file to disk

    # Parameters
    filepath (str): The directory to write the file to. This is often the
        run directory for a magicc instance. If None is passed,
        an error is raised.
    filename (str): The filename to write. Overrides any existing values.
        If None is passed, the filename used to initialise the MAGICCData
        instance is used.
    """
```

**Comment by rgieseke** [comment]
Instead of `filepath=None` couldn't we have `filepath=pymagicc._MAGICCBINARY`?

(upper-casing the var to emphasize it's a constant)

I think it could be confusing to allow for overwriting the `filename` set in the initialisation function. Either we have a Data object or a Reader object. For the latter it might make sense to be able to read different files.

**Comment by lewisjared** [comment]
Ahh I see. I agree they should have the same signature. The path should be first and required (no default value). It would be even better if the first arg is `path_or_magicc` where you can pass a string referencing a directory or a MAGICC instance, in which case the `run_dir` parameter is used.

I agree with @rgieseke. The filename could be dropped in preference for always defining the filename when initialising the object. This might clarify things.

`pymagicc._MAGICCBINARY` would refer to the executable not the run directory. I don't like the idea of the default of referencing the distributed configuration in MAGICC as changes to this distribution will persist across runs. This could make it difficult to debug issues in future

**Comment by znicholls** [comment]
> The filename could be dropped in preference for always defining the filename when initialising the object. This might clarify things.

Ok so would we then need to make a public `Reader` class? And should `MAGICCData` be able to write or should you have to pass it to separate `Writer` class first?

**Comment by znicholls** [comment]
> I don't like the idea of the default of referencing the distributed configuration in MAGICC as changes to this distribution will persist across runs.

I also don't like this.

**Comment by znicholls** [comment]
> By removing the `filename` parameter you can assume that `self.filename` is already defined before the call to read/write. This simplifies the logic in these functions a little.

I think this makes most sense, will tweak in future

**Comment by znicholls** [comment]
@rgieseke what did we discuss about this the other day? I've lost my notes...

**Comment by rgieseke** [comment]
Hmm, something like ...

- a convenience function in MAGICC which used the path of the MAGICC instance.
- `filepath` can be a full path including the filename.
- a directory should be `path`

**Comment by znicholls** [comment]
How would you feel about having a function signature like
'read(filepath=None, path_and_name=None)' so the user can either give the
filepath or the path and name (as a list like) and if they give both an
error is thrown?

**Comment by rgieseke** [comment]
`path_and_name` would be filepath, wouldn't it?

I think the reason to split was to be able to read from different paths or different files from the same path, right?

**Comment by rgieseke** [comment]
I don't see the point of the tuple -- you could also do this in code, right?

```python
source = "name.txt"
mdata.read(filepath="path/to.file/" + source)
```

**Comment by rgieseke** [comment]
The `MAGICCData` could also have a similar directory attribute as `MAGICC6`

```python
mdata = MAGICCData()
mdata.dir = "path/to/files"
mdata.read("names.txt")
```

**Comment by znicholls** [comment]
> I don't see the point of the tuple -- you could also do this in code, right?

Yep. I dunno, just thought it was a convenience some might like (and would `os.path.join` to avoid people joining paths incorrectly on different systems...)



> The `MAGICCData` could also have a similar directory attribute as `MAGICC6`

I'll implement something then we can talk more
