### ISSUE TITLE
MAGICC7 shipping

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#48]
When this happens, can we ship with a minimal `run` directory. The tests being so slow because we're copying so many files for MAGICC7 is driving me insane.

**Comment by lewisjared** [comment]
Check to see if your problems are solved in master.
@rgieseke It would be great to have a version bump so that the magicc tests could use the latest version. Currently the tests are pinned to a older commit.

**Comment by rgieseke** [comment]
Will do soon, there are a couple of nice new features!

As for speeding it up, maybe the MAGICC tests can re-use one Pymagicc copy more? Haven't checked yet in depth how they are set-up.
The main reason for copying is that you don't want multiple calls interfering, but in a testing setup this should be no problem (rather only in a parallel setup).

Otherwise, from a cursory web search it seems that using native copying tools with `subprocess` might be faster. 
Another idea (not tested at all), maybe copying one zip file and unpacking could be faster than copying many, many files.

**Comment by lewisjared** [comment]
@znicholls Do the tests run faster for you now?

**Comment by znicholls** [comment]
yes but I think it will be even faster if we ship with a tidy MAGICC7 repo

**Comment by lewisjared** [comment]
All of the shipped MAGICC7 bundles will be tidy! Well, that is the intent
anyway..
